import type { Metadata } from 'next';
import { Eyebrow, PillLink, Square } from '@/components/portfolio';
export const metadata: Metadata = { title: 'About', description: 'The winding path from sales, hospitality, and freelance music to product design. Meet Aneesh.' };

const experience = [
  { company: 'Metaveo', href: 'https://www.metaveo.ai/', role: 'UI/UX Designer and Brand Strategist', dates: 'April 2026 — Present', duration: '6 months' },
  { company: 'HCI Australia', href: 'https://www.hcigroup.com.au/', role: 'UI/UX Designer', dates: 'Jan 2024 — March 2026', duration: '2.3 years' },
  { company: 'Zoople Technologies', href: 'https://zoople.in/', role: 'UI/UX Intern', dates: 'Aug — Sept 2023', duration: '2 months' },
];

export default function AboutPage() {
  return <main id="main-content"><section className="about-hero shell"><div className="about-hero-copy"><Eyebrow>Behind the design</Eyebrow><h1>I make complex<br />things clear<Square /></h1></div><figure><img src="/assets/aneesh-portrait-rolled-sleeves.png" width="525" height="738" alt="Black and white portrait of Aneesh in a rolled-sleeve shirt, looking toward the camera." /></figure><div className="about-hero-action"><p>I design clear, useful digital products and brands that help people get things done.</p><PillLink href="/works">Explore my work</PillLink></div></section><section className="about-narrative shell" aria-label="Approach to design"><div className="about-narrative-copy"><Eyebrow>How I work</Eyebrow><div className="about-narrative-body"><p>My path into design has been shaped by the people I have worked alongside. Talented designers and developers have challenged my thinking, shared what they know, and helped me grow with every project.</p><p>I enjoy working directly with clients to understand their goals and turn them into useful digital experiences. I also mentor junior designers, sharing feedback and support so they can build confidence and do their best work.</p></div></div></section><section className="experience-section dark"><div className="shell"><div className="experience-heading"><Eyebrow>Experience</Eyebrow><h2>Places, roles,<br />and chapters<Square /></h2><p>A snapshot of the teams, responsibilities, and roles that have shaped how I approach the work.</p></div><ol className="experience-list">{experience.map((item, index) => <li key={item.company}><span className="experience-index">{String(index + 1).padStart(2, '0')}</span><div className="experience-company"><h3><a href={item.href} target="_blank" rel="noreferrer">{item.company}</a></h3><p>{item.role}</p></div><div className="experience-dates"><span>{item.dates}</span><strong>{item.duration}</strong></div></li>)}</ol></div></section></main>;
}
